-- MySQL Script generated by MySQL Workbench
-- Sun Dec 14 12:14:55 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ldrbrdv2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ldrbrdv2` ;

-- -----------------------------------------------------
-- Schema ldrbrdv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ldrbrdv2` DEFAULT CHARACTER SET latin1 ;
USE `ldrbrdv2` ;

-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_competition` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_competition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `competition_name` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `competitor_limit` INT(11) NULL DEFAULT NULL,
  `organising_society` INT(11) NULL DEFAULT NULL,
  `organising_golfer` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_competition_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_competition_entry` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_competition_entry` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `competition_id` INT(11) NOT NULL,
  `golfer_id` INT(11) NOT NULL,
  `entry_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_scoring_format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_scoring_format` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_scoring_format` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `format_name` VARCHAR(45) NOT NULL,
  `scoring_class` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_competition_round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_competition_round` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_competition_round` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `competition_id` INT(11) NOT NULL,
  `round_number` INT(11) NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `course_did` VARCHAR(45) NOT NULL,
  `scoring_format_id` INT(11) NULL DEFAULT NULL,
  `initial_tee_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cmptnnrnd_cmpttn_fk_idx` (`competition_id` ASC),
  INDEX `cmpttn_rnd_scrng_frmt_idx` (`scoring_format_id` ASC),
  CONSTRAINT `cmpttn_rnd_cmpttn`
    FOREIGN KEY (`competition_id`)
    REFERENCES `ldrbrdv2`.`ldrbrd_competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cmpttn_rnd_scrng_frmt`
    FOREIGN KEY (`scoring_format_id`)
    REFERENCES `ldrbrdv2`.`ldrbrd_scoring_format` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_scorecard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_scorecard` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_scorecard` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_did` VARCHAR(45) NOT NULL,
  `golfer_id` INT(11) NOT NULL,
  `round_date` DATETIME NOT NULL,
  `conditions` VARCHAR(45) NULL DEFAULT NULL,
  `handicap` VARCHAR(45) NULL DEFAULT NULL,
  `scorecard_notes` VARCHAR(45) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `scorecard_signature` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_competition_round_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_competition_round_score` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_competition_round_score` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `competition_entry_id` INT(11) NOT NULL,
  `scorecard_id` INT(11) NOT NULL,
  `competition_round_id` INT(11) NOT NULL,
  `golfer_signature` VARCHAR(45) NULL DEFAULT NULL,
  `scorer_signature` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `scorecard_id_idx` (`scorecard_id` ASC),
  INDEX `competition_round_idx` (`competition_round_id` ASC),
  CONSTRAINT `competition_round`
    FOREIGN KEY (`competition_round_id`)
    REFERENCES `ldrbrdv2`.`ldrbrd_competition_round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scorecard_id`
    FOREIGN KEY (`scorecard_id`)
    REFERENCES `ldrbrdv2`.`ldrbrd_scorecard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_golfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_golfer` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_golfer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `profile_handle` VARCHAR(45) NOT NULL,
  `handicap` INT(11) NULL DEFAULT '18',
  `email_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profile_name_UNIQUE` (`profile_handle` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ldrbrdv2`.`ldrbrd_hole_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ldrbrdv2`.`ldrbrd_hole_score` ;

CREATE TABLE IF NOT EXISTS `ldrbrdv2`.`ldrbrd_hole_score` (
  `scorecard_id` INT(11) NOT NULL,
  `hole_number` INT(11) NOT NULL,
  `score` INT(11) NOT NULL,
  `hole_did` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`scorecard_id`, `hole_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
